name: redux_todo_app
description: "A todo app made with redux"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  get_it: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  redux: ^5.0.0
  sqlite3: ^2.4.6

dev_dependencies:
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
