name: redux_todo_app
description: "A todo app made with redux"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  drift: ^2.20.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  redux: ^5.0.0

dev_dependencies:
  drift_dev: ^2.20.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
